service: notes
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  createNote:
    handler: handler.createNote
    events:
      - http:
          path: note
          method: post

  updateNote:
    handler: handler.updateNote
    events:
      - http:
          path: note/{id}
          method: put

  deleteNote:
    handler: handler.deleteNote
    events:
      - http:
          path: note/{id}
          method: delete

  getAllNotes:
    handler: handler.getAllNotes
    events:
      - http:
          path: note
          method: get

# you can add CloudFormation resource templates here
resources:
 Resources:
   NewResource:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: Notes
       BillingMode: PAY_PER_REQUEST
       AttributeDefinitions:
          - AttributeName: notesId
            AttributeType: S
       KeySchema:
          - AttributeName: notesId
            KeyType: HASH


